apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: nats
  namespace: production
spec:
  selector:
    matchLabels:
      app: nats
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 1m
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: "(gnatsd_varz_cluster_name|gnatsd_varz_connections|gnatsd_varz_cpu|gnatsd_varz_gateway_name|gnatsd_varz_in_bytes|gnatsd_varz_out_bytes|gnatsd_varz_in_msgs|gnatsd_varz_out_msgs|gnatsd_varz_max_connections|gnatsd_varz_mem|gnatsd_varz_routes|gnatsd_varz_server_id|gnatsd_varz_subscriptions|gnatsd_varz_total_connections|)"
          action: keep