apiVersion: autoscaling.gke.io/v1beta1
kind: MultidimPodAutoscaler
metadata:
  name: asterisk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ast
  goals:
    metrics:
      - type: Resource
        resource:
          # Define the target CPU utilization request here
          name: cpu
          target:
            type: Utilization
            averageUtilization: 90
  constraints:
    global:
      minReplicas: 1
      maxReplicas: 5
    containerControlledResources: [ memory ]
    container:
      - name: '*'
        # Define boundaries for the memory request here
        requests:
          minAllowed:
            memory: 1Gi
          maxAllowed:
            memory: 2Gi
  policy:
    updateMode: Auto