apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: asterisk
  namespace: production
spec:
  selector:
    matchLabels:
      component: asterisk
  podMetricsEndpoints:
    - port: http
      path: /metrics
      scheme: http
      interval: 1m
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: "(asterisk_active_user_calls)"
          action: drop