apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: db
  namespace: production
spec:
  selector:
    matchLabels:
      app: db
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 1m
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: "(mysql_global_status_connections|mysql_global_status_opened_files|mysql_global_status_queries|mysql_global_status_threads_connected|mysql_global_status_threads_running|mysql_global_status_uptime|mysql_slave_status_slave_io_running|mysql_slave_status_slave_sql_running|mysql_up)"
          action: keep
---
apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: db-commands
  namespace: production
spec:
  selector:
    matchLabels:
      app: db
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 1m
      metricRelabelings:
        - sourceLabels: [command]
          regex: "(insert|delete|select|update)"
          action: keep