apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: production
  labels:
    app: db
spec:
  ports:
    - name: mysql
      port: 3306
  selector:
    app: db
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: production
spec:
  ports:
    - port: 3306
  selector:
    app: db
  clusterIP: None