resources:
  - ../../base/kamailio
namespace: staging
images:
  - name: ghcr.io/voxoco/kamailio
    newName: ghcr.io/voxoco/kamailio
    newTag: kemi
  - name: ghcr.io/voxoco/kamailio-sidecar
    newName: ghcr.io/voxoco/kamailio-sidecar
    newTag: dev